[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
		
[[headers]]
  for = "/*/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
		
[[headers]]
  for = "/*/*/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"